services:
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis-service
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 0.5
        reservations:
          memory: 256M
          cpus: 0.25

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
