services:
  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo-service
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: developer
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 1.0
        reservations:
          memory: 256M
          cpus: 0.5

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
