version: "3"

services:
  postgres:
    image: postgres
    restart: on-failure
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: developer
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data

    networks:
      - postgres-network

volumes:
  postgresql-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
