services:
  mysqlsrv:
    image: mysql
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 1.0
        reservations:
          memory: 256M
          cpus: 0.5

networks:
  mysql-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
