version: "3"

services:
  keycloak:
    container_name: keycloak
    restart: on-failure
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: leosamblas
      KEYCLOAK_PASSWORD: developer

    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
