services:
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: on-failure
    ports:
      - 8978:8978
    volumes:
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - cloudbeaver-network
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: 1.0
        reservations:
          memory: 256M
          cpus: 0.5

networks:
  cloudbeaver-network:
    driver: bridge

volumes:
  cloudbeaver:
    driver: local
