services:
  database:
    image: container-registry.oracle.com/database/free:latest
    hostname: oracle
    container_name: oracle-service
    restart: on-failure
    environment:
      ORACLE_SID: FREE
      ORACLE_PDB: FREEPDB1
      ORACLE_PWD: developer
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    ports:
      - 1521:1521
    networks:
      - oracledb-network
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: 2.0
        reservations:
          memory: 512M
          cpus: 0.5

networks:
  oracledb-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local

  oracle-backup:
    driver: local
