version: "3"

services:
  database:
    image: container-registry.oracle.com/database/free:23.2.0.0
    container_name: oracle
    restart: on-failure
    environment:
      ORACLE_SID: FREE
      ORACLE_PDB: FREEPDB1
      ORACLE_PWD: developer
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - oracledb-network

networks:
  oracledb-network:
    driver: bridge

volumes:
  oracle-data:
  oracle-backup:
