version: "3.8"

services:
  localstack:
    container_name: localstack-main
    image: localstack/localstack
    restart: on-failure
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - localstack-data:/var/lib/localstack
      - localstack-data:/var/run/docker.sock
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge

volumes:
  localstack-data:
    driver: local