services:
  postgres:
    image: postgres
    restart: always
    container_name: postgresql-service
    hostname: postgresql
    environment:
      POSTGRES_PASSWORD: developer
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./ext_data:/ext_data
    networks:
      - postgres-network
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: 8.0
        reservations:
          memory: 1024M
          cpus: 4.0

volumes:
  postgresql-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
