# Pre reqs
# mkdir -p /apps/oracle/oradata
# chown -R 54321:54321 /apps/oracle/oradata
version: '3'
services:
  database:    
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    container_name: oracle
    restart: on-failure
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: developer
      DB_DOMAIN: oracle.leosamblas.com

    volumes:
      - /apps/oracle/oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
      - 5500:5500

    networks:
      - oracledb-network

networks: 
   oracledb-network:
    driver: bridge

### Trocar senha pelo terminal do container ###
# source /home/oracle/.bashrc; sqlplus /nolog
# connect sys as sysdba;
# password: Oradoc_db1
# alter user sys identified by developer;
### Criar usuario ###
# alter session set "_ORACLE_SCRIPT"=true;
# create user leosamblas identified by developer;
# GRANT ALL PRIVILEGES TO leosamblas;