services:
  database:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    hostname: oracle
    container_name: oracle-service
    restart: on-failure
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: developer
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
      - ./ext_data:/ext_data
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - oracledb-network
    deploy:
      resources:
        limits:
          memory: 4096M
          cpus: 8.0
        reservations:
          memory: 1024M
          cpus: 4.0

networks:
  oracledb-network:
    driver: bridge

volumes:
  oracle-data:
    driver: local

  oracle-backup:
    driver: local
### Trocar senha pelo terminal do container ###
# source /home/oracle/.bashrc; sqlplus /nolog
# connect sys as sysdba;
# password: Oradoc_db1
# alter user sys identified by developer;
### Criar usuario ###
# alter session set "_ORACLE_SCRIPT"=true;
# create user leosamblas identified by developer;
# GRANT ALL PRIVILEGES TO leosamblas;
