services:
  localstack:
    image: localstack/localstack:stable
    hostname: localstack
    container_name: localstack-service    
    restart: always
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - localstack-data:/var/lib/localstack
      - localstack-data:/var/run/docker.sock
    networks:
      - localstack-network
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: 1.0
        reservations:
          memory: 512M
          cpus: 0.5

networks:
  localstack-network:
    driver: bridge

volumes:
  localstack-data:
    driver: local
