version: '3'

services:
  mysqlsrv:
    image: mysql
    container_name: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
    ports:
      - 3306:3306
    volumes:
      - /home/leosamblas/desenvolvimento/docker/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8082:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge