services:
  postgres:
    image: postgres
    restart: on-failure
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: developer
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgres-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: 1.0
        reservations:
          memory: 256M
          cpus: 0.5

volumes:
  postgresql-data:
    driver: local

networks:
  postgres-network:
    driver: bridge
